WITH TEMP AS (
    SELECT 
       FSD.ORDERID FDORDERID,CC.ISCLOSED,CC.CLOSEDDATE,SD.ID DEPTID,SD.SHORTNAME DEPTNAME,SD.ORDERID DORDERID,ST.TYPEID,SDT.NAME TYPENAME,
       PA.ABILITY,
       MM.PLAN CM_PLAN,DF.COMPLETE,
       round(mm.plan/fn_getlastday('${fillinDate}'),5)cd_plan,
       round(mm.plan/fn_getlastday('${fillinDate}')*fn_getcurrentday('${fillinDate}'),5)cmamass_plan,
       FN_CMAMASS_COMPLETE('${fillinDate}',sd.id,pn.id,0) cmamass_complete,
       FN_CYAMASS_PLAN('${fillinDate}',sd.id,pn.id)cyamass_plan,
       FN_CYAMASS_COMPLETE('${fillinDate}',sd.id,pn.id,0) cyamass_complete
    FROM SYSDEPTANDPDNORM DP
	INNER JOIN SYSDEPT SD ON SD.ID = DP.SYSDEPTID
	INNER JOIN SYSDEPT FSD ON FSD.NO = SUBSTR(SD.NO,0,6)
    INNER JOIN PD_NORM PN ON PN.ID = DP.PDNORMID
    INNER JOIN SYSDEPTANDTYPE ST ON ST.DEPTID = SD.ID AND ST.TYPEID IN(9,10,11)
    INNER JOIN SYSDEPTTYPE SDT ON SDT.ID = ST.TYPEID
	INNER JOIN HNNY_COALTYPE_CONFIG CC ON CC.DEPTID = SD.ID
    LEFT JOIN HNNY_DAYREPORT_FILLIN DF ON DF.DEPTID = SD.ID AND DF.NORMID = PN.ID AND DF.FILLINDATE = '${fillinDate}'
    LEFT JOIN HNNY_PROD_ABILITY PA ON PA.DEPTID = SD.ID
    left join hnny_monthplan_mine mm 
    on mm.deptid = sd.id and mm.normid = pn.id and mm.month = substr('${fillinDate}',0,7) 
	where sd.isdel = 'N' and dp.pdnormid = 2 
	and sd.no like (
		select fsd.no from sysdept fsd where fsd.id = ${fdeptId} and fsd.isdel = 'N'
	)||'%'
)
SELECT '${fillinDate}' fillinDate,B.* FROM (
    SELECT 
        -1 FDORDERID,1 DEPTID,0 ISCLOSED,'' CLOSEDDATE,'合计' DEPTNAME,-1 DORDERID,-1 TYPEID,
        SUM(T.ABILITY)ABILITY,SUM(T.CM_PLAN)CM_PLAN,
        SUM(T.CD_PLAN)CD_PLAN,SUM(T.COMPLETE)COMPLETE,
        SUM(T.CMAMASS_PLAN)CMAMASS_PLAN,SUM(T.CMAMASS_COMPLETE)CMAMASS_COMPLETE,
        SUM(T.CYAMASS_COMPLETE)CYAMASS_COMPLETE
    FROM TEMP T WHERE T.TYPEID IN(9,10) --这里排除掉 11本部矿井数据，应为9省内中已经包含了本部数据
    GROUP BY -1,1,'合计',-1,-1
    UNION ALL
    SELECT 
        -1 FDORDERID,1 DEPTID,0 ISCLOSED,'' CLOSEDDATE,T.TYPENAME DEPTNAME,1 DORDERID,T.TYPEID,
        SUM(T.ABILITY)ABILITY,SUM(T.CM_PLAN)CM_PLAN,
        SUM(T.CD_PLAN)CD_PLAN,SUM(T.COMPLETE)COMPLETE,
        SUM(T.CMAMASS_PLAN)CMAMASS_PLAN,SUM(T.CMAMASS_COMPLETE)CMAMASS_COMPLETE,
        SUM(T.CYAMASS_COMPLETE)CYAMASS_COMPLETE
    FROM TEMP T
    GROUP BY -1,1,T.TYPENAME,1,T.TYPEID
    UNION ALL
    SELECT 
        T.FDORDERID,T.DEPTID,T.ISCLOSED,T.CLOSEDDATE,T.DEPTNAME,T.DORDERID,T.TYPEID,
        SUM(T.ABILITY)ABILITY,SUM(T.CM_PLAN)CM_PLAN,
        SUM(T.CD_PLAN)CD_PLAN,SUM(T.COMPLETE)COMPLETE,
        SUM(T.CMAMASS_PLAN)CMAMASS_PLAN,SUM(T.CMAMASS_COMPLETE)CMAMASS_COMPLETE,
        SUM(T.CYAMASS_COMPLETE)CYAMASS_COMPLETE
    FROM TEMP T WHERE T.TYPEID IN(9,10) --这里排除掉 11本部矿井数据，应为9省内中已经包含了本部数据
    GROUP BY T.FDORDERID,T.DEPTID,T.ISCLOSED,T.CLOSEDDATE,T.DEPTNAME,T.DORDERID,T.TYPEID
)B
ORDER BY B.FDORDERID,B.DORDERID,B.TYPEID